Update golden.md
Kometa-Team/Kometa pull request #2322
Opened 2024-11-14 07:35 UTC by antwanchild

corrected example on Golden from Emmy to Golden Globes

## Description

Please include a summary of the changes.

### Issues Fixed or Closed

- Fixes #(issue)

## Type of Change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation change (non-code changes affecting only the wiki)
- [] Infrastructure change (changes related to the github repo, build process, or the like)

## Checklist

Please delete options that are not relevant.

- [] Updated Documentation to reflect changes
- [] Updated the CHANGELOG with the changes

2024-11-14 15:32 UTC, chazlarson requested changes
Please fill out the PR form and link this to the related issue.

2024-11-15 22:01 UTC, antwanchild commented
i think i did what @chazlarson has asked

2024-11-15 22:15 UTC, chazlarson approved these changes

2024-11-16 13:22 UTC, YozoraXCII commented
Fixes #2322 2321

2024-11-16 13:23 UTC, merged